### ISSUE TITLE
[BUG] JobLvl Command

### ISSUE THREAD

**Issue by sajmon094** [NosAdventure/bugs-reports#12] opened 2021-06-25 19:36 UTC
**Describe the bug**
When u type in chat $JLvl u got message : New skill learned and the job is still the same
^
**To Reproduce**

**Expected behavior**
Command should give job instead of getting new skill.
**Screenshots | GIF**
If applicable, add screenshots or a GIF to help explain your problem.

**Comment by Erwann9875** [comment] 2021-06-29 14:24
Have been fixed by Lucifer

**Closed as completed by Erwann9875** 2021-06-29 14:24 UTC
Labels: bug

**Comment by sajmon094** [comment] 2021-06-29 19:32
Now it says wrong value 
![image](https://user-images.githubusercontent.com/86253629/123856527-7e3ce400-d921-11eb-9127-8307fee97beb.png)

**Comment by Erwann9875** [comment] 2021-06-29 19:33
Not a bug, that's because you're class 0 and you're trying to set a joblevel > to 20

**Comment by sajmon094** [comment] 2021-06-29 19:35
Yeah, my bad sorry for that

**Comment by Erwann9875** [comment] 2021-06-29 19:35
No problem, thanks for ur contribution anyway
